# Generated by Django 6.0.5 on 2026-05-19 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_post_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='views',
        ),
        migrations.AddField(
            model_name='post',
            name='views',
            field=models.BigIntegerField(default=0),
        ),
    ]
